name: CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  id-token: write

jobs:

  # --------------------------------------------------
  # 1. Run application tests
  # --------------------------------------------------
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: backend
        run: |
          python -m pytest -v


  # --------------------------------------------------
  # 2. Build Docker image and push to ECR
  # --------------------------------------------------
  docker-build-push:
    runs-on: ubuntu-latest
    needs: test

    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::303164492950:role/ecommerce-devops-github-actions
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/ecommerce-devops-backend:${{ github.sha }} \
            ./backend

      - name: Push Docker image to ECR
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/ecommerce-devops-backend:${{ github.sha }}


  # --------------------------------------------------
  # 3. Update DEV environment
  # --------------------------------------------------
  update-gitops:
    runs-on: ubuntu-latest
    needs: docker-build-push

    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v7
        with:
          repository: vikashsum/ecommerce-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: ecommerce-gitops

      - name: Update DEV image tag
        working-directory: ecommerce-gitops
        run: |
          sed -i "s/newTag: .*/newTag: ${{ github.sha }}/" overlays/dev/kustomization.yaml

      - name: Commit and push DEV change
        working-directory: ecommerce-gitops
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add overlays/dev/kustomization.yaml

          git commit \
            -m "Update backend image to ${{ github.sha }}" \
            || echo "No changes to commit"

          git push origin main


  # --------------------------------------------------
  # 4. Promote SAME image SHA to STAGING
  # --------------------------------------------------
  promote-staging:
    runs-on: ubuntu-latest
    needs: update-gitops

    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v7
        with:
          repository: vikashsum/ecommerce-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: ecommerce-gitops

      - name: Update STAGING image tag
        working-directory: ecommerce-gitops
        run: |
          sed -i "s/newTag: .*/newTag: ${{ github.sha }}/" overlays/staging/kustomization.yaml

      - name: Commit and push STAGING change
        working-directory: ecommerce-gitops
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add overlays/staging/kustomization.yaml

          git commit \
            -m "Promote backend image to staging: ${{ github.sha }}" \
            || echo "No changes to commit"

          git push origin main